"""
Mock Test Manager Module
========================
Handles retrieval of exam-relevant context from the local ChromaDB vector store,
generation of 20-question mock tests (10 RAG-extracted, 10 AI-generated), and
grading of user test submissions using LLMs.
"""

import os
import re
import json
import random
from typing import List, Dict, Optional
from langchain_core.messages import SystemMessage, HumanMessage
from src.agent.database import VectorCache
from src.agent.graph import get_llm

def get_rag_test_chunks(paper: str, subjects: List[str] = None, limit: int = 50) -> List[Dict]:
    """
    Retrieves exam-relevant chunks from ChromaDB, prioritizing PYQs, practice papers, 
    and detailed guides matching the subject filter.
    """
    db = VectorCache()
    # Semantic search targeted at finding questions and practice problems
    query = "GATE exam question previous year paper practice problem multiple choice NAT numerical exercise"
    query_embeddings = db.model.encode(query).tolist()
    
    # Restrict to active paper and general info
    where_filter = {"source": {"$in": [paper, "general"]}}
    
    results = db.collection.query(
        query_embeddings=[query_embeddings],
        n_results=limit,
        where=where_filter
    )
    
    documents = results.get("documents", [[]])[0]
    metadatas = results.get("metadatas", [[]])[0]
    
    chunks = []
    for doc, meta in zip(documents, metadatas):
        file_path = meta.get("file_path", "").lower()
        
        # If subjects are specified, filter chunks matching the selected subject ID keywords
        if subjects:
            if not any(sub_id.lower() in file_path or sub_id.lower().replace("-", "_") in file_path for sub_id in subjects):
                continue
                
        # Prioritize PYQ, practice papers, notes, study material
        is_valuable = any(k in file_path for k in ["pyq", "question", "paper", "practice", "notes", "rbr", "madeeasy"])
        if is_valuable:
            chunks.append({
                "content": doc,
                "metadata": meta
            })
            
    return chunks

def generate_mock_test(paper: str, test_type: str, subjects: List[str]) -> List[Dict]:
    """
    Generates a 20-question mock test (10 extracted from RAG chunks, 10 generated by AI).
    Each question object has:
      - id: int (1 to 20)
      - source_type: str ("pyq" or "generated")
      - subject_id: str
      - question_text: str
      - options: Optional[List[str]] (length 4, or null/empty for NAT)
      - correct_answer: str (e.g. "A", "B", "C", "D" or exact numerical value/range)
      - explanation: str
    """
    llm = get_llm()
    
    # 1. Gather RAG context chunks
    rag_chunks = get_rag_test_chunks(paper, subjects if test_type == "subject" else None, limit=60)
    # Shuffle and slice to get random sample
    random.shuffle(rag_chunks)
    selected_chunks = rag_chunks[:25]
    
    context_str = ""
    for idx, chunk in enumerate(selected_chunks):
        file_name = chunk.get("metadata", {}).get("file_name", "Study Guide")
        context_str += f"\n--- Source: {file_name} ---\n{chunk['content']}\n"

    subjects_str = ", ".join(subjects) if subjects else "all core subjects"
    
    # Prompt for RAG question extraction
    rag_prompt = (
        f"You are a GATE exam mock test compiler for the GATE {paper.upper()} stream.\n"
        f"Your task is to extract exactly 10 high-quality questions from the study materials and previous year papers context provided below.\n\n"
        f"Context from study materials:\n{context_str}\n\n"
        f"Selected Subjects/Scope: {subjects_str}\n\n"
        "Instructions:\n"
        "1. Extract/formulate exactly 10 exam-style questions. All of these should be directly sourced or closely adapted from the context.\n"
        "2. The questions must be a mix of Multiple Choice Questions (MCQs) and Numerical Answer Type (NAT) questions.\n"
        "3. For MCQs, provide exactly 4 options (labeled A, B, C, D) inside a JSON array.\n"
        "4. For NATs, provide null for options, and describe the correct answer range or number.\n"
        "5. Output your result ONLY as a valid JSON array of objects. Do not wrap it in ```json ... ``` markdown fences or write any conversational text. Follow this schema exactly:\n"
        "[\n"
        "  {\n"
        "    \"id\": 1,\n"
        "    \"source_type\": \"pyq\",\n"
        "    \"subject_id\": \"subject-id-here\",\n"
        "    \"question_text\": \"...\",\n"
        "    \"options\": [\"Option A\", \"Option B\", \"Option C\", \"Option D\"],\n"
        "    \"correct_answer\": \"A\",\n"
        "    \"explanation\": \"...\"\n"
        "  }\n"
        "]"
    )
    
    # Prompt for AI question generation
    gen_prompt = (
        f"You are a GATE exam mock test generator for the GATE {paper.upper()} stream.\n"
        f"Generate exactly 10 new, realistic GATE-style questions (MCQs or NATs) covering the following subjects/scope: {subjects_str}.\n\n"
        "Instructions:\n"
        "1. Create exactly 10 questions covering core concepts of the syllabus.\n"
        "2. Ensure questions range in difficulty (from basic to highly analytical).\n"
        "3. Provide exactly 4 options (labeled A, B, C, D) for MCQs inside a JSON array.\n"
        "4. Provide null for options in NATs.\n"
        "5. Output your result ONLY as a valid JSON array of objects matching this schema. Do not write any explanations outside the JSON:\n"
        "[\n"
        "  {\n"
        "    \"id\": 11,\n"
        "    \"source_type\": \"generated\",\n"
        "    \"subject_id\": \"subject-id-here\",\n"
        "    \"question_text\": \"...\",\n"
        "    \"options\": [\"Option A\", \"Option B\", \"Option C\", \"Option D\"],\n"
        "    \"correct_answer\": \"B\",\n"
        "    \"explanation\": \"...\"\n"
        "  }\n"
        "]"
    )

    try:
        # Run RAG extraction
        rag_res = llm.invoke([HumanMessage(content=rag_prompt)])
        rag_json_str = clean_json_response(rag_res.content)
        rag_questions = json.loads(rag_json_str)
    except Exception as e:
        print(f"Error generating RAG questions: {e}. Falling back to default generation.")
        rag_questions = []

    try:
        # Run AI generation
        gen_res = llm.invoke([HumanMessage(content=gen_prompt)])
        gen_json_str = clean_json_response(gen_res.content)
        gen_questions = json.loads(gen_json_str)
    except Exception as e:
        print(f"Error generating AI questions: {e}")
        gen_questions = []

    # If generation failed or returned incomplete list, build mock questions to avoid crashing
    if len(rag_questions) < 10 or len(gen_questions) < 10:
        print("Incomplete questions generated. Re-generating unified list...")
        unified_prompt = (
            f"Generate exactly 20 mock test questions for the GATE {paper.upper()} syllabus covering: {subjects_str}.\n"
            "Make exactly 10 of them labeled with \"source_type\": \"pyq\" (simulated PYQ questions) and 10 labeled with \"source_type\": \"generated\".\n"
            "Output your result ONLY as a valid JSON array of objects matching the schema. No markdown wrapping:\n"
            "[\n"
            "  {\n"
            "    \"id\": 1,\n"
            "    \"source_type\": \"pyq\",\n"
            "    \"subject_id\": \"subject-id\",\n"
            "    \"question_text\": \"...\",\n"
            "    \"options\": [\"Option A\", \"Option B\", \"Option C\", \"Option D\"],\n"
            "    \"correct_answer\": \"C\",\n"
            "    \"explanation\": \"...\"\n"
            "  }\n"
            "]"
        )
        try:
            unif_res = llm.invoke([HumanMessage(content=unified_prompt)])
            unif_json_str = clean_json_response(unif_res.content)
            all_questions = json.loads(unif_json_str)
            # Re-index
            for idx, q in enumerate(all_questions):
                q["id"] = idx + 1
            return all_questions
        except Exception as ex:
            print(f"Critical error generating unified mock test: {ex}")
            # return static dummy questions as a last resort safeguard
            return get_fallback_questions(paper, subjects)

    # Re-index all questions sequentially (1 to 20)
    all_questions = []
    for idx, q in enumerate(rag_questions[:10] + gen_questions[:10]):
        q["id"] = idx + 1
        all_questions.append(q)
        
    random.shuffle(all_questions)
    # Re-index again after shuffle so presentation is 1..20
    for idx, q in enumerate(all_questions):
        q["id"] = idx + 1
        
    return all_questions

def clean_json_response(content: str) -> str:
    """Removes markdown backticks and extra text surrounding the JSON array response."""
    cleaned = content.strip()
    if cleaned.startswith("```"):
        # remove starting ```json or ```
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        # remove ending ```
        cleaned = re.sub(r"\s*```$", "", cleaned)
    return cleaned.strip()

def evaluate_mock_test(questions: List[Dict], user_answers: Dict[str, str]) -> Dict:
    """
    Grades user answers using the LLM.
    Returns:
      - score: int
      - evaluations: List[Dict] (each element contains: id, correct (bool), feedback, correct_answer)
    """
    llm = get_llm()
    
    test_data = []
    for q in questions:
        q_id = str(q["id"])
        user_ans = user_answers.get(q_id, "").strip()
        test_data.append({
            "id": q["id"],
            "question_text": q["question_text"],
            "correct_answer": q["correct_answer"],
            "user_answer": user_ans,
            "explanation": q["explanation"]
        })
        
    evaluation_prompt = (
        "You are an expert GATE exam evaluator. Grade the user's answers for a 20-question mock test.\n"
        "For each question, check if the user's answer matches the correct answer. "
        "For Multiple Choice, a match must align with the correct option letter. "
        "For Numerical Answer Type (NAT), a match should be mathematically equal or lie within standard tolerance ranges described.\n\n"
        f"Test Data JSON:\n{json.dumps(test_data, indent=2)}\n\n"
        "Provide your evaluation output ONLY as a valid JSON object matching the following structure. Do not wrap in markdown tags or write anything else:\n"
        "{\n"
        "  \"score\": 14,\n"
        "  \"evaluations\": [\n"
        "    {\n"
        "      \"id\": 1,\n"
        "      \"correct\": true,\n"
        "      \"feedback\": \"Correct! The explanation holds...\",\n"
        "      \"correct_answer\": \"A\"\n"
        "    }\n"
        "  ]\n"
        "}"
    )
    
    try:
        res = llm.invoke([SystemMessage(content="You are a strict grading assistant. Output ONLY valid JSON."), HumanMessage(content=evaluation_prompt)])
        json_str = clean_json_response(res.content)
        result = json.loads(json_str)
        return result
    except Exception as e:
        print(f"Error evaluating mock test: {e}")
        # fallback evaluation logic: simple direct string compare
        evaluations = []
        score = 0
        for q in questions:
            q_id = str(q["id"])
            user_ans = user_answers.get(q_id, "").strip().upper()
            correct_ans = str(q["correct_answer"]).strip().upper()
            
            is_correct = user_ans == correct_ans
            if is_correct:
                score += 1
            evaluations.append({
                "id": q["id"],
                "correct": is_correct,
                "feedback": "Graded using basic comparison. " + q["explanation"],
                "correct_answer": q["correct_answer"]
            })
        return {"score": score, "evaluations": evaluations}

def get_fallback_questions(paper: str, subjects: List[str] = None) -> List[Dict]:
    """Generates fallback dummy questions in case of API/connectivity failures."""
    return [
        {
            "id": i,
            "source_type": "generated",
            "subject_id": "engineering-mathematics" if paper == "cs" else "probability-and-statistics",
            "question_text": f"Fallback Mock Question {i}: What is the time complexity of binary search on a sorted list?",
            "options": ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
            "correct_answer": "B",
            "explanation": "Binary search divides the search space in half at each step, resulting in a logarithmic runtime complexity."
        }
        for i in range(1, 21)
    ]
